<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <PackageId>MediasiteUtil.Law.Ucdavis.Edu</PackageId>
    <Authors>UC Davis School of Law</Authors>
    <Description>Mediasite API Client for reading and writing to some of the available Mediasite API endpoints.</Description>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl>gitproj/MediasiteUtil</RepositoryUrl>
    <PackageTags>Mediasite API REST Client</PackageTags>
    <PackageReleaseNotes>Initial release</PackageReleaseNotes>
    <Version>1.0.6</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

</Project>
